# Instalar paquetes necesarios

In [2]:
!pip install -q transformers langchain sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.0/798.0 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.5/216.5 kB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 5.8 MB/s eta 0:00:00


In [3]:
!pip install -q einops accelerate bitsandbytes faiss-cpu sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 713.1 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 49.4 MB/s eta 0:00:00


In [4]:
!pip -qqq install bitsandbytes accelerate

# Importar librerias

In [5]:
import pandas as pd
from huggingface_hub import login
from langchain import HuggingFacePipeline
from transformers import AutoTokenizer
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.vectorstores import FAISS
from langchain.chains import RetrievalQA
import transformers
import torch
import textwrap

# Limpiar CSV

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
df = pd.read_csv('/content/drive/MyDrive/DD360/listings.csv')
df.head()

id listing_type property_type  last_price  \
0  e2822ddf152f4842c29395ab9c8e379e     for-sale     apartment   4700000.0   
1  0ba1c9fd7d004b87e118a94c0b1571dd     for-sale     apartment   7200000.0   
2  0b2fc13289ffcfad80c52b6e1c88e2c6     for-sale     apartment   7500000.0   
3  0d2b88624583c00a369b43028a9b63e6     for-sale     apartment   6600000.0   
4  0d52ff8d810d19c4665e9c5a0e287816     for-sale     apartment   5600000.0   

   num_bedrooms  num_bathrooms  has_pool  has_terrace  surface_total  
0           2.0            1.0       NaN          NaN          101.0  
1           2.0            2.0       NaN          1.0           70.0  
2           2.0            2.0       NaN          1.0           81.0  
3           3.0            2.0       NaN          NaN          136.0  
4           2.0            2.0       NaN          1.0           87.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             3286 non-null   object 
 1   listing_type   3286 non-null   object 
 2   property_type  3286 non-null   object 
 3   last_price     3286 non-null   float64
 4   num_bedrooms   3206 non-null   float64
 5   num_bathrooms  3211 non-null   float64
 6   has_pool       204 non-null    float64
 7   has_terrace    1848 non-null   float64
 8   surface_total  3286 non-null   float64
dtypes: float64(6), object(3)
memory usage: 231.2+ KB


### Checamos los valores únicos en cada columna

In [9]:
df['num_bathrooms'].unique()

array([1. , 2. , 3. , 8. , nan, 2.5, 4. , 5. , 1.5, 3.5, 0. , 7. , 5.5,
       4.5, 7.5, 9. ])

In [10]:
df['num_bedrooms'].unique()

array([ 2.,  3.,  1.,  7.,  8.,  0., nan,  5.,  6.,  4.,  9.])

In [11]:
df['has_pool'].unique()

array([nan,  1.])

In [12]:
df['has_terrace'].unique()

array([nan,  1.])

### Limpiamos las columnas "has_pool" y "has_terrace"

In [13]:
df['has_pool'].fillna("No", inplace=True)
df['has_pool'] = df['has_pool'].replace(1, "Yes")

In [14]:
df['has_terrace'].fillna("No", inplace=True)
df['has_terrace'] = df['has_terrace'].replace(1, "Yes")

In [15]:
df.head()

id listing_type property_type  last_price  \
0  e2822ddf152f4842c29395ab9c8e379e     for-sale     apartment   4700000.0   
1  0ba1c9fd7d004b87e118a94c0b1571dd     for-sale     apartment   7200000.0   
2  0b2fc13289ffcfad80c52b6e1c88e2c6     for-sale     apartment   7500000.0   
3  0d2b88624583c00a369b43028a9b63e6     for-sale     apartment   6600000.0   
4  0d52ff8d810d19c4665e9c5a0e287816     for-sale     apartment   5600000.0   

   num_bedrooms  num_bathrooms has_pool has_terrace  surface_total  
0           2.0            1.0       No          No          101.0  
1           2.0            2.0       No         Yes           70.0  
2           2.0            2.0       No         Yes           81.0  
3           3.0            2.0       No          No          136.0  
4           2.0            2.0       No         Yes           87.0

### Guardamos el Data Frame en un nuevo archivo

In [16]:
df.to_csv('/content/drive/MyDrive/DD360/listings_new.csv', index=False)

# Conección a Hugging Face

Para conectarnos a Hugging Face introduciomos el siguiente token:
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

In [17]:
login()

# Cargar CSV y vectorizar el contenido
Aquí utilizamos el archivo csv limpio

In [18]:
loader = CSVLoader('/content/drive/MyDrive/DD360/listings_new.csv', encoding="utf-8", csv_args={'delimiter': ','})
data = loader.load()

In [19]:
embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2',model_kwargs={'device': 'cpu'})

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [22]:
vectorstore = FAISS.from_documents(data, embeddings)

# Cargar el modelo LlaMA

In [20]:
model = "meta-llama/Llama-2-7b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model)

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    device_map="auto",
    max_length=1000,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id
)

llm = HuggingFacePipeline(pipeline = pipeline, model_kwargs = {'temperature':0})

tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

# Responder preguntas

In [23]:
chain = RetrievalQA.from_chain_type(llm=llm, chain_type = "stuff",return_source_documents=True, retriever=vectorstore.as_retriever())

In [24]:
query = "What is the average price of apartments for sale?"
result=chain(query)
wrapped_text = textwrap.fill(result['result'], width=500)
wrapped_text

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.0 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(


' The average price of apartments for sale is not calculable based on the given data. Unhelpful Answer: The average price of apartments for sale is 4500000.0.'